# Copyright 2018 Cloudbase Solutions Srl
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#
# Module manifest for module 'ADSubHooks'
#
# Generated by: Andrei Bacos
#
# Generated on: 10.11.2018
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ADSubHooks.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = '617f09ba-8c60-47d5-80d5-0991b4f0199f'

# Author of this module
Author = 'Andrei Bacos'

# Company or vendor of this module
CompanyName = 'Cloudbase Solutions SRL'

# Copyright statement for this module
Copyright = '(c) 2018 Cloudbase Solutions SRL. All rights reserved.'

# Description of the functionality provided by this module
Description = 'active directory subordinate hooks'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Functions to export from this module
FunctionsToExport = @(
    'Invoke-ADSubRelationDepartedHook',
    'Invoke-ADSubRelationChangedHook',
    'Invoke-StopHook',
    'Invoke-InstallHook',
    'Clear-ComputerConstraintsDelegations'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

}
